### ISSUE TITLE
anusvara errors

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/hwnorm1#16]
In [normalization.pdf](https://github.com/sanskrit-lexicon/hwnorm1/blob/master/normalization.pdf), Dhaval mentions, on page 2, 

> When anusvAra occurs before any of the letters  य,र,ल,व,श,ष,स or ह, it is uniformly depicted as
anusvAra in all dictionaries.

A check in hwnorm1c.txt finds three exceptions: 
```
3 matches for "^[^:]*M[^yrlvSzsh:]" in buffer: hwnorm1c.txt
 219690:nayavartMan:nayavartMan:SCH
 229022:nFMHpraRetra:nFMHpraRetra:MW
 270685:BIzMacaRqika:BIzMacaRqika:PUI
```

The SCH example is a digitization typo that should be corrected:
![image](https://user-images.githubusercontent.com/6393033/72845117-ec30a680-3c6b-11ea-8cd9-d3b7b3dad6df.png)

The PUI example looks to be a print error, that also should be corrected to BIzmacaRqika:
![image](https://user-images.githubusercontent.com/6393033/72845272-3c0f6d80-3c6c-11ea-8bff-a27686e1d42c.png)

The MW example is less clear. See next comment.

**Comment by funderburkjim** [comment]
There are three similarly spelled words in hwnorm1c.txt:
```
nFMHpraRetra:nFMHpraRetra:MW
nFnHpraRetra:nFnHpraRetra:MW
nF~HpraRetra:nF~HpraRetra:PW,PWG
```
The '~' in PW, PWG is the SLP representation of candrabindu.

Here are the scanned images:
nFnHpraRetra  MW  'leading men'
(scan is hard to see here -- someone wrote on the page before scan made):
![image](https://user-images.githubusercontent.com/6393033/72845688-2b132c00-3c6d-11ea-9aa4-0e278ba8de44.png)

nFMHpraRetra MW : see nf
![image](https://user-images.githubusercontent.com/6393033/72845903-8cd39600-3c6d-11ea-834c-1976b9bf0b5b.png)

nF~HpraRetra PW
![image](https://user-images.githubusercontent.com/6393033/72846234-32870500-3c6e-11ea-8fc5-cb0549a398ed.png)

nF~HpraRetra PWG
![image](https://user-images.githubusercontent.com/6393033/72846367-70842900-3c6e-11ea-9d45-00666519d848.png)


As PWG says, nFn is acc. pl. of nf (slp1 spelling).  Why visarga interposes is questionable, and why
the 'n' then becomes candra-bindu is a question.

Not sure what, if any, changes need to be made .  Are all correct?

Relative to the goal of uniform spelling, clearly all three spellings refer to the same word.

**Comment by drdhaval2785** [comment]
nF~praRetra is the correct version. MW needs to be corrected. Also see a dIrgha mark above `i` and chandrabindu above `n` in IAST representation.

**Comment by funderburkjim** [comment]
> nF~praRetra is the correct version

I don't see the visarga.   Did you mean `nF~HpraRetra`.

**Comment by drdhaval2785** [comment]
Sorry. nF~HpraRetra.

**Comment by funderburkjim** [comment]
Corrections made for sch, pui, and mw.   (pw and pwg need no change).
