### ISSUE TITLE
Add Lanman (to 7 places)

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/hwnorm1#17]
A few steps in this repository were needed for Lanman to be available in the simple-search
display of csl-apidev repository.

See  [this commit](https://github.com/sanskrit-lexicon/hwnorm1/commit/17c600bd40f4888924ea0ea0288b4e2ea1adc41d).

* add LAN to dictionary lists of [sanhw1.py](https://github.com/sanskrit-lexicon/hwnorm1/blob/master/sanhw1/sanhw1.py)
* remake (by instructions in [sanhw1 readme](https://raw.githubusercontent.com/sanskrit-lexicon/hwnorm1/master/sanhw1/readme.org)
  * sanhw1.txt
  * hwnorm1c
  * `mv hwnorm1c.sqlite ../../csl-apidev/simple-search/hwnorm1/`   
    * then csl-apidev repository must be synced.

**Comment by drdhaval2785** [comment]
Based on recent interaction, all places which require placement of 'lan' or 'LAN' for code to run, have been attended to. Closing.

**Comment by gasyoun** [comment]
> all places which require placement of 'lan' or 'LAN' 

Do we have a list now what are the places, for if we would want to add any Sanskrit-Sanskrit dictionaries in the future?

**Comment by funderburkjim** [comment]
Adding a new dictionary requires changes in
* csl-pywork/v02
* csl-websanlexicon/v02
* csl-orig/v02
* csl-homepage
* csl-docs (for front matter)
* and for images, a new repository in sanskrit-lexicon-scans Github organization.
* and for images at Cologne, a 'pdfpages' folder
   For Lanman, this was scans/LANScan/2019/web/pdfpages

Exactly what in these repositories needs changing --  no definite list.  The system isn't modularized 
to the degree that a CMS might be.

**Comment by gasyoun** [comment]
> Adding a new dictionary requires changes in

7 places, thanks.
