### ISSUE TITLE
a blank headword in LAN in sanhw1.txt

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/hwnorm1#18]
The very first line in sanhw1.txt shows the following
```
:LAN
```
i.e. a blank headword. Kindly correct the same.

**Comment by funderburkjim** [comment]
The blank headword was 3rd homonym of vayas, L=3702.

Now corrected.

Updates done for 
* csl-orig repository
* hwnorm1  repository
  * follow instructions 1-4 of hwnorm1/sanhw1/readme.txt for updates to sanhw1.txt and hwnorm1c.txt
* csl-apidev  repository (for new binary csl-apidev/simple-search/hwnorm1/hwnorm1c.sqlite)
   * hwnorm1 instructions above does this move in local installation
* In csl-pywork/v02,  regenerate lan .

**Comment by gasyoun** [comment]
> Updates done for

Thanks for the sample list.
